export const metricsArray = [
    {
        title: 'Color consistency',
        description: 'Colour consistency includes the percentage of predefined colours in relation to the total number of colours used. Ideally, only the predefined colours are used. Currently, only local styles (within the design) can be used for evaluation.',
        resultSentenceSingle: 'A colour used in the design is not one of the predefined colours.',
        resultSentenceMultiple: 'Some colours used in the design are not among the predefined colours.',
        thresholds: { green: { min: 100, max: 100 }, yellow: { min: 50, max: 99 }, red: { min: 0, max: 49 } },
        multipleFrames: false,
    },
    {
        title: 'Font consistency',
        description: 'Font consistency comprises the percentage of predefined font formats in relation to the total number of font formats used. A font format can include the font family, size, style, colour and other font characteristics such as character spacing. Only (a few) predefined font formats should be used. Currently, only local styles (within the design) can be used for evaluation.',
        resultSentenceSingle: 'A font format used in the design is not one of the predefined font formats.',
        resultSentenceMultiple: 'Some font formats used in the design are not among the predefined font formats.',
        thresholds: { green: { min: 100, max: 100 }, yellow: { min: 50, max: 99 }, red: { min: 0, max: 49 } },
        multipleFrames: false,
    },
    {
        title: 'Reference to homepage',
        description: 'For a website with more than one page, all pages should have a link back to the homepage/startpage. Only the homepage itself does not need to be linked to itself.',
        resultSentenceSingle: 'A page does not have a link to the homepage.',
        resultSentenceMultiple: 'Some pages do not have links to the homepage.',
        thresholds: { green: { min: 1, max: 1 }, yellow: { min: 0.5, max: 0.99 }, red: { min: 0, max: 0.49 } },
        multipleFrames: true,
    },
    {
        title: 'Orphan pages',
        description: 'Orphan pages are part of a website, but none of the other pages on the website refer to them, so they cannot be reached via an internal link. They worsen the navigability of a website and should therefore be avoided.',
        resultSentenceSingle: 'A page is an orphan page and cannot be reached within the application.',
        resultSentenceMultiple: 'Some pages are orphaned pages and cannot be reached within the application.',
        thresholds: { green: { min: 0, max: 0 }, yellow: { min: 0.1, max: 0.5 }, red: { min: 0.51, max: 1 } },
        multipleFrames: true,
    },
    {
        title: 'Font size',
        description: 'A font size of at least 12pt should be used on web pages.',
        resultSentenceSingle: 'A text field has a font size smaller than 12pt.',
        resultSentenceMultiple: 'Some text fields have a font size smaller than 12pt.',
        thresholds: null,
        multipleFrames: false,
    },
];